#!/bin/sh
#/etc/init.d/ServerAdministration
#
# thanks to this user
# Marcio S Galli (@taboca)
# http://labs.telasocial.com/nodejs-forever-daemon/
#

#forever path
export PATH=$PATH:/usr/local/bin
#node modules path
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
#port to run server.
PORT=3000
#sourceDir
SOURCEDIR=/home/santi8ago8/GitHub/ServerAdministration

start(){
    exec PORT=$PORT forever start --sourceDir=$SOURCEDIR -p $SOURCEDIR/forever.pid -l $SOURCEDIR/forever.log --append --uid="ServerAdministration" app.js
}
stop(){
    exec forever stop ServerAdministration
}
case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    status)
        echo forever logs 0
	;;
    *)
        echo "Usage: /etc/init.d/ServerAdministration {start|stop|status|restart}"
        exit 1
    ;;
esac

exit 0
